[build]
exclude = [
    "/README.md",
]

  [[build.buildpacks]]
  uri = "paketo-buildpacks/web-servers"

  [[ build.env ]]
    name="BP_NODE_VERSION"
    value="18.15.0"

  [[ build.env ]]
    name="BP_NODE_RUN_SCRIPTS"
    value="build"

  [[ build.env ]]
    name="BP_HTTPD_VERSION"
    value="2.4.46"

  [[ build.env ]]
    name="BP_WEB_SERVER"
    value="httpd"

  [[ build.env ]]
    name="BP_WEB_SERVER_ROOT"
    value="dist/web-app-layer"

  [[ build.env ]]
    name="BP_WEB_SERVER_ENABLE_PUSH_STATE"
    value="true"

  [[ build.env ]]
    name="BP_WEB_SERVER_FORCE_HTTPS"
    value="false"
