[server]
port = 8686
[build]
exclude = [
    "/README.md",
]

  [[build.buildpacks]]
  uri = "paketo-buildpacks/web-servers"

  [[ build.env ]]
    name="BP_NODE_VERSION"
    value="18.15.0"


  [[ build.env ]]
    name="BP_NODE_RUN_SCRIPTS"
    value="build:nginx"

  [[ build.env ]]
    name="BP_WEB_SERVER"
    value="nginx"

  [[ build.env ]]
    name="BP_WEB_SERVER_ROOT"
    value="dist/web-app-layer"

  [[ build.env ]]
    name="BP_WEB_SERVER_ENABLE_PUSH_STATE"
    value="true"

  [[ build.env ]]
    name="BP_WEB_SERVER_FORCE_HTTPS"
    value="false"
