# MIME types
[media_types]
  [media_types.html]
    suffixes = ["html", "htm"]
    encoding = "UTF-8"
    type = "text/html"
  [media_types.jpg]
    suffixes = ["jpg", "jpeg"]
    type = "image/jpeg"
  [media_types.png]
    suffixes = ["png"]
    type = "image/png"
  [media_types.js]
    suffixes = ["js"]
    encoding = "UTF-8"
    type = "application/javascript"

[build]
exclude = [
    "/README.md",
]

  [[build.buildpacks]]
  uri = "paketo-buildpacks/web-servers"

  [[ build.env ]]
    name="BP_NODE_RUN_SCRIPTS"
    value="build"

  [[ build.env ]]
    name="BP_WEB_SERVER"
    value="nginx"

  [[ build.env ]]
    name="BP_WEB_SERVER_ROOT"
    value="dist/web-app-layer"

  [[ build.env ]]
    name="BP_WEB_SERVER_ENABLE_PUSH_STATE"
    value="true"

  [[ build.env ]]
    name="BP_WEB_SERVER_FORCE_HTTPS"
    value="false"
